websocket_irc_server: "wss://irc-ws.chat.twitch.tv/"
websocket_pubsub_server: "wss://pubsub-edge.twitch.tv"
websocket_local_server: localhost
websocket_local_port: 80
amqp_server: localhost
amqp_exchange: "topic_twitch_servitor"
topics:
  webhook: "topic.twitch.follows"
  pubsub: "topic.twitch.subscriptions"
  irc: "topic.twitch.hosts"
nickname: "Karmik"
irc_channel: "#karmik"
channel_id: "7578596"