websocket_irc_server: "wss://irc-ws.chat.twitch.tv/"
websocket_pubsub_server: "wss://pubsub-edge.twitch.tv"
websocket_local_server: localhost
websocket_local_port: 80
aqmp_server: localhost
aqmp_exchange: "topic_twitch_servitor"
topics:
  - "topic.twitch.follows"
  - "topic.twitch.subscriptions"
  - "topic.twitch.hosts"
nickname: "Karmik"
irc_channel: "#karmik"